version: "3.8"

services:
  api:
    image: blessing67/emart-nodeapi:${VERSION:-latest}
    ports:
      - "5000:5000"
    restart: unless-stopped
    container_name: api
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://emongo:27017/epoc
    depends_on:
      - emongo
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  emongo:
    image: mongo:4
    container_name: emongo
    environment:
      - MONGO_INITDB_DATABASE=epoc
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: