version: "3.8"

services:
  nginx:
    image: blessing67/emart-client:${VERSION:-latest}
    container_name: nginx
    ports:
      - "80:4200"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped