all:
  hosts:
    client_nginx:
      ansible_host: 13.51.166.62
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/Downloads/vprofile-prod.pem


    node_mongo:
      ansible_host: 13.62.76.96
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/Downloads/vprofile-prod.pem


    java_mysql:
      ansible_host: 51.20.54.156
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/Downloads/vprofile-prod.pem

