service: emart-nodeapi
image: blessing67/emart-nodeapi

ssh:
  user: ubuntu

servers:
  web:
    hosts:
      - 16.171.24.148
    options:
      publish:
        - "5000:5000"

registry:
  username: blessing67
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    NODE_ENV: production
    MONGODB_URI: mongodb://emart-nodeapi-emongo:27017/epoc

builder:
  arch: amd64
  dockerfile: nodeapi/Dockerfile
  context: .

proxy:
  host: false

accessories:
  emongo:
    image: mongo:4
    host: 16.171.24.148
    port: "27017:27017"
    env:
      MONGO_INITDB_DATABASE: epoc
    directories:
      - /home/ubuntu/data:/data/db