service: emart-client
image: blessing67/emart-client

ssh:
  user: ubuntu

servers:
  web:
    hosts:
      - 16.171.23.91
    options:
        healthcheck:
           interval: 0  # Disables health check 

registry:
  username: blessing67
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  dockerfile: client/Dockerfile
  context: .

proxy:
  host: 16.171.23.91
