secrets:
  - .kamal/secrets.age
service: emartapp-dev
image: blessing67/emartapp
servers:
  web:
    hosts:
      - 16.171.23.91:22  # Server 1: Nginx + Client
    labels:
      traefik.http.routers.emartapp-dev.rule: "Host(`dev.emartapp.yourdomain.com`)"  # Replace with dev domain
  nodeapi:
    hosts:
      - 16.171.24.148:22  # Server 2: Node.js API + MongoDB
    labels:
      traefik.http.routers.emartapi-dev.rule: "Host(`api.dev.emartapp.yourdomain.com`)"  # Replace with dev domain
  javaapi:
    hosts:
      - 13.60.25.27:22  # Server 3: Java API + MySQL
    cmd: "--spring.profiles.active=dev"
    labels:
      traefik.http.routers.emartjava-dev.rule: "Host(`java.dev.emartapp.yourdomain.com`)"  # Replace with dev domain
registry:
  username: blessing67
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  clear:
    NODE_ENV: development
    SPRING_PROFILES_ACTIVE: dev
  secret:
    - MYSQL_ROOT_PASSWORD
    - MYSQL_DATABASE
    - MONGO_INITDB_DATABASE
builder:
  multi: true
  args:
    client:
      context: ./client
    nodeapi:
      context: ./nodeapi
    javaapi:
      context: ./javaapi
    nginx:
      context: ./nginx
traefik:
  args:
    - "--entrypoints.web.address=:80"
volumes:
  - "/var/run/docker.sock:/var/run/docker.sock:ro"
accessories:
  emongo:
    image: mongo:4
    host: 51.21.182.191:22
    port: "27017:27017"
    env:
      MONGO_INITDB_DATABASE: epoc
    directories:
      - data:/data/db
  emartdb:
    image: mysql:8.0.33
    host: 13.61.34.198:22
    port: "3306:3306"
    env:
      MYSQL_ROOT_PASSWORD: emartdbpass
      MYSQL_DATABASE: books
    directories:
      - data:/var/lib/mysql