name: Deploy Production Services

on:
  push:
    branches: [main]
    paths:
      - 'services/**'
      - 'infrastructure/docker-compose/**'
      - 'infrastructure/nginx/**'
      - '.github/workflows/deploy-day1.yml'
  workflow_dispatch:

concurrency:
  group: deploy-production
  cancel-in-progress: true  # Auto-cancel redundant runs

env:
  DOCKER_REGISTRY: blessing67
  VERSION: ${{ github.sha }}

jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [client, nodeapi, javaapi]

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_REGISTRY }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push ${{ matrix.service }}
        run: |
          cd services/${{ matrix.service }}
          docker build --pull -t ${{ env.DOCKER_REGISTRY }}/emart-${{ matrix.service }}:${{ env.VERSION }} . | tee ../../logs/${{ matrix.service }}-build.log
          docker tag ${{ env.DOCKER_REGISTRY }}/emart-${{ matrix.service }}:${{ env.VERSION }} ${{ env.DOCKER_REGISTRY }}/emart-${{ matrix.service }}:latest
          docker push ${{ env.DOCKER_REGISTRY }}/emart-${{ matrix.service }}:${{ env.VERSION }} | tee -a ../../logs/${{ matrix.service }}-build.log
          docker push ${{ env.DOCKER_REGISTRY }}/emart-${{ matrix.service }}:latest | tee -a ../../logs/${{ matrix.service }}-build.log

      - name: Upload build logs
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.service }}-build-log
          path: logs/${{ matrix.service }}-build.log

  deploy-nodeapi:
    needs: build-images
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 51.21.180.27 >> ~/.ssh/known_hosts

      - name: Deploy Node API
        run: |
          mkdir -p logs
          {
          scp -i ~/.ssh/id_rsa infrastructure/docker-compose/docker-compose.nodeapi.yml ubuntu@51.21.180.27:~/
          ssh -i ~/.ssh/id_rsa ubuntu@51.21.180.27 << 'EOF'
            export VERSION=${{ env.VERSION }}
            docker-compose -f docker-compose.nodeapi.yml down || true
            docker-compose -f docker-compose.nodeapi.yml pull
            docker-compose -f docker-compose.nodeapi.yml up -d
            sleep 15
          EOF
          } 2>&1 | tee logs/nodeapi-deploy.log

      - name: Health check Node API
        run: |
          mkdir -p logs
          {
          for i in {1..2}; do
            if curl -f http://51.21.180.27:5000/health 2>/dev/null; then
              echo "Node API is healthy"
              exit 0
            fi
            echo "Attempt $i/2 failed, retrying..."
            sleep 5
          done
          echo "Node API health check failed"
          exit 1
          } 2>&1 | tee logs/nodeapi-health.log

      - name: Upload Node API logs
        uses: actions/upload-artifact@v3
        with:
          name: nodeapi-logs
          path: logs/

  deploy-javaapi:
    needs: build-images
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 51.21.200.51 >> ~/.ssh/known_hosts

      - name: Deploy Java API
        run: |
          mkdir -p logs
          {
          scp -i ~/.ssh/id_rsa infrastructure/docker-compose/docker-compose.javaapi.yml ubuntu@51.21.200.51:~/
          ssh -i ~/.ssh/id_rsa ubuntu@51.21.200.51 << 'EOF'
            export VERSION=${{ env.VERSION }}
            docker-compose -f docker-compose.javaapi.yml down || true
            docker-compose -f docker-compose.javaapi.yml pull
            docker-compose -f docker-compose.javaapi.yml up -d
            sleep 20
          EOF
          } 2>&1 | tee logs/javaapi-deploy.log

      - name: Health check Java API
        run: |
          mkdir -p logs
          {
          for i in {1..2}; do
            if curl -f http://51.21.200.51:9000/health 2>/dev/null; then
              echo "Java API is healthy"
              exit 0
            fi
            echo "Attempt $i/2 failed, retrying..."
            sleep 5
          done
          echo "Java API health check failed"
          exit 1
          } 2>&1 | tee logs/javaapi-health.log

      - name: Upload Java API logs
        uses: actions/upload-artifact@v3
        with:
          name: javaapi-logs
          path: logs/

  deploy-client:
    needs: [deploy-nodeapi, deploy-javaapi]
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 13.60.196.137 >> ~/.ssh/known_hosts

      - name: Deploy Client
        run: |
          mkdir -p logs
          {
          ssh -i ~/.ssh/id_rsa ubuntu@13.60.196.137 'mkdir -p ~/nginx'
          scp -i ~/.ssh/id_rsa infrastructure/docker-compose/docker-compose.client.yml ubuntu@13.60.196.137:~/
          scp -i ~/.ssh/id_rsa infrastructure/nginx/default.conf ubuntu@13.60.196.137:~/nginx/
          ssh -i ~/.ssh/id_rsa ubuntu@13.60.196.137 << 'EOF'
            export VERSION=${{ env.VERSION }}
            docker-compose -f docker-compose.client.yml down || true
            docker-compose -f docker-compose.client.yml pull
            docker-compose -f docker-compose.client.yml up -d
            sleep 10
          EOF
          } 2>&1 | tee logs/client-deploy.log

      - name: Health check Client
        run: |
          mkdir -p logs
          {
          for i in {1..2}; do
            if curl -f http://13.60.196.137 2>/dev/null; then
              echo "Client is healthy"
              exit 0
            fi
            echo "Attempt $i/2 failed, retrying..."
            sleep 5
          done
          echo "Client health check failed"
          exit 1
          } 2>&1 | tee logs/client-health.log

      - name: Upload Client logs
        uses: actions/upload-artifact@v3
        with:
          name: client-logs
          path: logs/

      - name: Verify deployment
        run: |
          echo "Deployment complete!"
          echo "Node API: http://51.21.180.27:5000"
          echo "Java API: http://51.21.200.51:9000"
          echo "Client: http://13.60.196.137"
