name: Setup Infrastructure with Ansible

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  setup-infrastructure:
    name: Setup Server Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible boto3 botocore

      - name: Setup SSH Key
        run: |
          SSH_DIR="${RUNNER_TEMP}/ssh"
          mkdir -p "$SSH_DIR"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > "$SSH_DIR/vprofile-prod.pem"
          chmod 600 "$SSH_DIR/vprofile-prod.pem"

          # Add hosts to known_hosts
          ssh-keyscan -H 13.51.166.62 >> "$SSH_DIR/known_hosts"
          ssh-keyscan -H 13.62.76.96 >> "$SSH_DIR/known_hosts"
          ssh-keyscan -H 51.20.54.156 >> "$SSH_DIR/known_hosts"

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory/hosts.yml \
            --private-key "${RUNNER_TEMP}/ssh/vprofile-prod.pem" \
            ansible/playbooks/main.yml
