name: Setup Infrastructure with Ansible

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  setup-infrastructure:
    name: Setup Server Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible boto3 botocore

          
      - name: Setup SSH Key
        shell: bash
        run: |
          set -euxo pipefail
          export SSH_DIR="${RUNNER_TEMP}/ssh"
          mkdir -p "$SSH_DIR"
          [[ -n "${{ secrets.SSH_PRIVATE_KEY }}" ]]
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > "$SSH_DIR/vprofile-prod.pem"
          chmod 600 "$SSH_DIR/vprofile-prod.pem"

          # scan each host individually; ignore failures
          for h in 13.51.166.62 13.62.76.96 51.20.54.156; do
          ssh-keyscan -H "$h" >> "$SSH_DIR/known_hosts" 2>/dev/null || echo "⚠️  $h unreachable"
          done
          echo "SSH_DIR=$SSH_DIR" >> "$GITHUB_ENV"

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory/hosts.yml \
            --private-key "${SSH_DIR}/vprofile-prod.pem" \
            ansible/playbooks/main.yml