# .github/workflows/setup-infra.yml
name: Setup Infrastructure with Ansible

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [main]

jobs:
  setup-infrastructure:
    name: Setup Server Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible boto3 botocore

      - name: Setup SSH Key
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/vprofile-prod.pem
          chmod 600 $HOME/.ssh/vprofile-prod.pem

          # Add all hosts to known_hosts
          ssh-keyscan -H 13.51.166.62 >> $HOME/.ssh/known_hosts   # client_nginx
          ssh-keyscan -H 13.62.76.96 >> $HOME/.ssh/known_hosts   # node_mongo
          ssh-keyscan -H 51.20.54.156 >> $HOME/.ssh/known_hosts  # java_mysql

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory/hosts.yml \
            --private-key $HOME/.ssh/vprofile-prod.pem \
            ansible/playbooks/main.yml
