name: Setup Infrastructure with Ansible

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  setup-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible boto3 botocore

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/vprofile-prod.pem
          chmod 600 ~/.ssh/vprofile-prod.pem
          ssh-keyscan -H 13.60.187.151 >> ~/.ssh/known_hosts
          ssh-keyscan -H 51.21.182.191 >> ~/.ssh/known_hosts
          ssh-keyscan -H 13.61.34.198 >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory/hosts.yml ansible/playbooks/main.yml --private-key ~/.ssh/vprofile-prod.pem
