name: Deploy with Kamal

on:
  push:
    branches: [main]
    paths:
      - 'config/deploy*.yml'
      - '.kamal/secrets*'
      - '.github/workflows/kamal-deploy.yml'
      - 'client/**'
      - 'nodeapi/**'
      - 'javaapi/**'
  workflow_dispatch:

concurrency:
  group: kamal-deploy
  cancel-in-progress: true

jobs:
  pre-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH Key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan 16.171.23.91 16.171.24.148 13.60.25.27 >> ~/.ssh/known_hosts

      - name: Pre-Deployment Checks
        run: |
          for server in 16.171.23.91 16.171.24.148 13.60.25.27; do
            ssh -i ~/.ssh/id_rsa ubuntu@$server "echo 'SSH OK' && docker --version" || exit 1
          done
          ssh -i ~/.ssh/id_rsa ubuntu@16.171.24.148 "mkdir -p /home/ubuntu/data && touch /home/ubuntu/data/test && rm /home/ubuntu/data/test"
          ssh -i ~/.ssh/id_rsa ubuntu@13.60.25.27 "mkdir -p /home/ubuntu/mysql && touch /home/ubuntu/mysql/test && rm /home/ubuntu/mysql/test"

  deploy-nodeapi:
    needs: pre-checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
    - run: gem install kamal
    
    - name: Setup SSH
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan 16.171.24.148 >> ~/.ssh/known_hosts

    - name: Deploy Node API
      run: |
        git pull origin main
        curl -fsSL https://github.com/FiloSottile/age/releases/download/v1.1.1/age-v1.1.1-linux-amd64.tar.gz | sudo tar -xzf - -C /usr/local/bin --strip-components=1
        age -d -i .kamal/secrets-age.txt -o .env.decrypted .kamal/secrets.age
        echo "Checking secrets..."
        grep MONGO_INITDB_DATABASE .env.decrypted || echo "MONGO missing!"
        set -a && source .env.decrypted && set +a
        export KAMAL_REGISTRY_PASSWORD="${{ secrets.DOCKER_HUB_PASSWORD }}"
        kamal deploy -c config/deploy-nodeapi.yml
        rm .env.decrypted

  deploy-javaapi:
    needs: deploy-nodeapi
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
    - run: gem install kamal
    
    - name: Setup SSH
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan 13.60.25.27 >> ~/.ssh/known_hosts

    - name: Deploy Java API
      run: |
        git pull origin main
        curl -fsSL https://github.com/FiloSottile/age/releases/download/v1.1.1/age-v1.1.1-linux-amd64.tar.gz | sudo tar -xzf - -C /usr/local/bin --strip-components=1
        age -d -i .kamal/secrets-age.txt -o .env.decrypted .kamal/secrets.age
        echo "Checking secrets..."
        grep MYSQL_ROOT_PASSWORD .env.decrypted || echo "MYSQL secrets missing!"
        set -a && source .env.decrypted && set +a
        export KAMAL_REGISTRY_PASSWORD="${{ secrets.DOCKER_HUB_PASSWORD }}"
        kamal deploy -c config/deploy-javaapi.yml
        rm .env.decrypted

  deploy-client:
    needs: [deploy-nodeapi, deploy-javaapi]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
    - run: gem install kamal
    
    - name: Setup SSH
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan 16.171.23.91 >> ~/.ssh/known_hosts

    - name: Deploy Client
      run: |
        git pull origin main
        curl -fsSL https://github.com/FiloSottile/age/releases/download/v1.1.1/age-v1.1.1-linux-amd64.tar.gz | sudo tar -xzf - -C /usr/local/bin --strip-components=1
        age -d -i .kamal/secrets-age.txt -o .env.decrypted .kamal/secrets.age
        set -a && source .env.decrypted && set +a
        export KAMAL_REGISTRY_PASSWORD="${{ secrets.DOCKER_HUB_PASSWORD }}"
        kamal deploy -c config/deploy-client.yml
        rm .env.decrypted